[04:29:2022 08:29:07 ERROR]std::exception. The program ran into a problem.
[04:29:2022 08:29:07 ERROR]Force exiting the program.
